import data from './data.json'
import palette from '../../lib/tailwind-palette'
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts'

export default function RenewablesMix() {
  return (
    <section className="py-24 flex flex-col items-center gap-8 w-full">
      <div className="w-full max-w-2xl">
        <h2 className="text-4xl max-w-2xl">
          Our first, most critical step is transitioning from{' '}
          <span className="text-amber-900">fossil fuels</span> to clean
          electricity.
        </h2>
        <p className="mt-4 mb-8">
          The proportion of electricity generated by renewable energy sources
          has more than tripled since 2010.
        </p>
      </div>

      <iframe
        title="Electricity Generation in Percentage of Terawatt-hours "
        aria-label="Stacked Column Chart"
        id="datawrapper-chart-5KCnY"
        src="https://datawrapper.dwcdn.net/5KCnY/19/"
        scrolling="no"
        frameBorder="0"
        height="446"
        width="100%"
        className="max-w-2xl"
      />

      <ResponsiveContainer
        width="100%"
        height="100%"
        minHeight={256}
        minWidth={256}
        className="max-w-2xl"
      >
        <BarChart
          width={500}
          height={300}
          data={data}
          margin={{
            top: 5,
            right: 5,
            left: 5,
            bottom: 5,
          }}
        >
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="Year" />
          <YAxis />
          <Tooltip
            separator=": "
            formatter={(value, name, item) => `${value}%`}
          />
          <Legend />
          <Bar dataKey="Coal" stackId="fossil" fill={palette.zinc[800]} />
          <Bar
            dataKey="Natural Gas"
            stackId="fossil"
            fill={palette.zinc[600]}
          />
          <Bar dataKey="Oil" stackId="fossil" fill={palette.zinc[400]} />
          <Bar dataKey="Nuclear" stackId="zero" fill={palette.orange[500]} />
          <Bar dataKey="Renewables" stackId="zero" fill={palette.lime[500]} />
          <Bar
            dataKey="Hydroelectricity"
            stackId="zero"
            fill={palette.blue[500]}
          />
          <Bar dataKey="Other" stackId="zero" fill={palette.red[500]} />
        </BarChart>
      </ResponsiveContainer>
    </section>
  )
}
